account_app/urls.py
from . import views
from django.urls import path

app_name = "accounts_app"
urlpatterns = [
    path("register", views.register_page, name="register"),
    path("login", views.login_page, name="login"),
    path("logout", views.logout_page, name="logout_page"),
]

deployDjango/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path("", include("home_app.urls")),
                  path("accounts/", include("account_app.urls"))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home_app/urls.py
from . import views
from django.urls import path

app_name = "home_app"
urlpatterns = [
    path("", views.home_page, name="main"),
    path("send_email", views.send_email, name="send_email"),
    path("email_sent_successfully", views.email_sent_successfully, name="email_sent_successfully"),
]

account_app/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser


class MyUserManager(BaseUserManager):
    def create_user(self, username, email=None, password=None):
        """
        Creates and saves a User with the given email, date of
        birth and password.
        """
        # if not username:
        #     raise ValueError("Users must have an username")

        if not email:
            raise ValueError('Users must have an email')

        if not username:
            raise ValueError("Users must have an username")

        user = self.model(
            username=username,
            email=email
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, password, email=None):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(
            username=username,
            email=email,
            password=password,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser):
    username = models.CharField(max_length=50, unique=True)
    password = models.CharField(max_length=100)
    email = models.EmailField(
        verbose_name="email address",
        max_length=255,
        unique=True
    )
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    objects = MyUserManager()

    USERNAME_FIELD = "username"
    REQUIRED_FIELDS = ["email"]

    def __str__(self):
        return f"{self.username} - {self.email}"

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin

home_app/models.py
from django.db import models

# Create your models here.

account_app/forms.py
from .models import User
from django import forms


class RegistrationForm(forms.Form):
    username = forms.CharField(max_length=50, required=True, widget=forms.TextInput())
    email = forms.EmailField(required=True, widget=forms.EmailInput())
    pass1 = forms.CharField(max_length=100, required=True, widget=forms.PasswordInput())
    pass2 = forms.CharField(max_length=100, required=True, widget=forms.PasswordInput())

    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data.get("username")
        email = cleaned_data.get('email')
        pass1 = cleaned_data.get("pass1")
        pass2 = cleaned_data.get("pass2")

        if pass1 and pass2 and pass1 != pass2:
            self.add_error("pass1", "Your passwords aren`t matched!")

        if User.objects.filter(username=username).exists() is True:
            self.add_error("username", "This Username exists!")

        if User.objects.filter(email=email).exists() is True:
            self.add_error("email", "This email exists!")

        User.objects.create_user(username=username, email=email, password=pass1)

account_app/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect

from account_app.forms import RegistrationForm


# Create your views here.


def register_page(request):
    if request.method == "POST":
        form = RegistrationForm(request.POST)
        if form.is_valid():
            return redirect("home_app:main")

    else:
        form = RegistrationForm()
        context = {
            "form": form,
        }
        return render(request, "account_app/register_page.html", context)


def login_page(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")

        user = authenticate(request=request, username=username, password=password)
        if user is not None:
            login(request=request, user=user)
            return redirect("home_app:main")
    else:
        form = RegistrationForm()
        context = {
            "form": form,
        }
        return render(request, "account_app/register_page.html", context)


def logout_page(request):
    if request.user.is_authenticated:
        logout(request)
        return redirect("accounts_app:register")

home_app/views.py
import redis
from django.shortcuts import render, redirect
from .tasks import send_async_email
from django.core.cache import cache
from deployDjango import settings

# Create your views here.

redis_client = redis.Redis(host="127.0.0.1", port=6379, db=0)


# Celery worker run: celery -A deployDjango worker --loglevel=info

def home_page(request):
    return render(request, "home_app/index.html")


def send_email(request):
    if request.method == "POST":
        data = request.POST
        email = data.get("email")
        subject = data.get("subject")
        message = data.get("message")

        redis_client.set("last_email", email, ex=60 * 2)  # This caches just last 2 minutes
        redis_client.set("last_email_subject", subject, ex=60 * 2)
        redis_client.set("last_email_message", message, ex=60 * 2)
        send_async_email(subject=subject, email=email, message=message)
        return redirect("home_app:email_sent_successfully")

    return render(request, "home_app/send_email.html")


def email_sent_successfully(request):
    # Retrieve the last email subject and message from Redis
    email = redis_client.get("last_email")
    subject = redis_client.get("last_email_subject")
    message = redis_client.get("last_email_message")

    email = email.decode('utf-8') if email else 'No email sent or it`s expired'
    subject = subject.decode('utf-8') if subject else 'No subject sent or it`s expired'
    message = message.decode('utf-8') if message else 'No message sent or it`s expired'

    context = {
        "email": email,
        'subject': subject,
        'message': message,
    }

    return render(request, "home_app/email_sent_successfully.html", context)

account_app/templates/account_app/register_page.html
{% load static %}
<!DOCTYPE html>
<!-- Coding by CodingLab | www.codinglabweb.com-->
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Responsive Login and Signup Form </title>

    <!-- CSS -->
    <link rel="stylesheet" href="{% static "css/accounts_css.css" %}">

    <!-- Boxicons CSS -->
    <link href='https://unpkg.com/boxicons@2.1.2/css/boxicons.min.css' rel='stylesheet'>

</head>

<body>
<section class="container forms">
    <div class="form login">
        <div class="form-content">
            <header>Login</header>
            <form action="{% url "accounts_app:login" %}" method="POST">
                {% csrf_token %}
                <div class="field input-field">
                    <input type="text" name="username" {% if form.username.value %}value="{{ form.username.value }}"{% endif %}
                           placeholder="username"
                           class="input">
                </div>

                <div class="field input-field">
                    <input type="password" name='password' placeholder="Password" class="password">
                    <i class='bx bx-hide eye-icon'></i>
                </div>

                <div class="form-link">
                    <a href="#" class="forgot-pass">Forgot password?</a>
                </div>

                <div class="field button-field">
                    <button>Login</button>
                </div>
            </form>

            <div class="form-link">
                <span>Don't have an account? <a href="#" class="link signup-link">Signup</a></span>
            </div>
        </div>

        <div class="line"></div>

        <div class="media-options">
            <a href="#" class="field facebook">
                <i class='bx bxl-facebook facebook-icon'></i>
                <span>Login with Facebook</span>
            </a>
        </div>

        <div class="media-options">
            <a href="#" class="field google">
                <img src="{% static "images/google.png" %}" alt="" class="google-img">
                <span>Login with Google</span>
            </a>
        </div>

    </div>
    <!-- Signup Form -->

    <div class="form signup">
        <div class="form-content">
            <header>Signup</header>
            <form action="{% url "accounts_app:register" %}" method="POST">
                {% csrf_token %}
                <div class="field input-field">
                    <input type="email" name="email" {% if form.email.value %}value="{{ form.email.value }}"{% endif %}
                           placeholder="Email"
                           class="input">
                </div>

                <div class="field input-field">
                    <input type="text" name="username"
                           {% if form.username.value %}value="{{ form.username.value }}"{% endif %}
                           placeholder="Username"
                           class="input">
                </div>

                <div class="field input-field">
                    <input type="password" name="pass1" placeholder="Create password" class="password">
                </div>
                {% if form.pass1.errors %}
                    <div class="text-danger">{{ form.pass1.errors }}</div>
                {% endif %}

                <div class="field input-field">
                    <input type="password" name="pass2" placeholder="Confirm password" class="password">
                    <i class='bx bx-hide eye-icon'></i>
                </div>

                <div class="field button-field">
                    <button type="submit">Signup</button>
                </div>
            </form>

            <div class="form-link">
                <span>Already have an account? <a href="#" class="link login-link">Login</a></span>
            </div>
        </div>

        <div class="line"></div>

        <div class="media-options">
            <a href="#" class="field facebook">
                <i class='bx bxl-facebook facebook-icon'></i>
                <span>Login with Facebook</span>
            </a>
        </div>

        <div class="media-options">
            <a href="#" class="field google">
                <img src="{% static "images/google.png" %}" alt="Google" class="google-img">
                <span>Login with Google</span>
            </a>
        </div>

    </div>
</section>

<!-- JavaScript -->
<script type="text/javascript">
    const forms = document.querySelector(".forms"),
        pwShowHide = document.querySelectorAll(".eye-icon"),
        links = document.querySelectorAll(".link");

    // Add click event listener to each eye icon for toggling password visibility
    pwShowHide.forEach(eyeIcon => {
        eyeIcon.addEventListener("click", () => {
            let pwFields = eyeIcon.parentElement.parentElement.querySelectorAll(".password");

            pwFields.forEach(password => {
                if (password.type === "password") { // If password is hidden
                    password.type = "text"; // Show password
                    eyeIcon.classList.replace("bx-hide", "bx-show"); // Change icon to show state
                    return;
                }
                password.type = "password"; // Hide password
                eyeIcon.classList.replace("bx-show", "bx-hide"); // Change icon to hide state
            });

        });
    });

    // Add click event listener to each link to toggle between forms
    links.forEach(link => {
        link.addEventListener("click", e => {
            e.preventDefault(); // Prevent default link behavior
            forms.classList.toggle("show-signup");
        });
    });
</script>
</body>

</html>

home_app/templates/home_app/email_sent_successfully.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Email Sent Successfully</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 20px;
            background-color: #f9f9f9;
            text-align: center;
        }

        p {
            font-size: 20px;
            color: #333;
            padding: 10px;
            border: 1px solid #ddd;
            border-radius: 5px;
            background: #fff;
            display: inline-block;
        }
    </style>
</head>
<body>
<h1>Email Sent Successfully</h1>
<img src="{% static "images/Redis.png" %}" width="400px" height="150px" alt="redis-image">
<h4 style="color: red; font-weight: bold;">This information that u are seeing are stored in redis` cache and they will
    expired in few minutes!</h4>
<p><strong>Email:</strong> {{ email }}</p>
<p><strong>Subject:</strong> {{ subject }}</p>
<p><strong>Message:</strong> {{ message }}</p>
<br>
<a href="{% url 'home_app:send_email' %}">Send another email</a>
<br>
<a href="{% url 'home_app:main' %}">Main Page</a>
</body>
</html>

home_app/templates/home_app/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <title>Nikolat27</title>
</head>
<body>

<nav class="navbar">
    <div class="navbar-container">
        <div class="navbar-logo">
            <a href="{% url "home_app:main" %}">MyApp</a>
        </div>
        <ul class="navbar-links">
            <li><a href="{% url "home_app:send_email" %}">Send Email</a></li>
            <li><a href="{% url "home_app:email_sent_successfully" %}">Check Status</a></li>
            <li><a href="{% url "accounts_app:login" %}">Login</a></li>
            <li><a href="{% url "accounts_app:register" %}">Sign Up</a></li>
        </ul>
    </div>
</nav>

<div align="center">
    <br>
    <img src="{% static "images/Django.png" %}" width="400px" height="300px" alt="">
    <img src="{% static "images/Docker.png" %}" width="400px" height="300px" alt="">
</div>

</body>
</html>

home_app/templates/home_app/send_email.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Email Selector</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 20px;
        }

        .container {
            max-width: 400px;
            background: white;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
            margin: auto;
        }

        h1 {
            text-align: center;
        }

        select, input[type="text"] {
            width: 100%;
            padding: 10px;
            margin: 10px 0;
            border: 1px solid #ccc;
            border-radius: 5px;
        }

        button {
            width: 100%;
            padding: 10px;
            background-color: #28a745;
            color: white;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }

        button:hover {
            background-color: #218838;
        }
    </style>
</head>
<body>

<div class="container">
    <h1>Select Email <br>(<span style="color: limegreen; font-weight: bold;">Using Celery</span>)</h1>
    <form method="POST">
        {% csrf_token %}
        <img src="{% static "images/Celery.png" %}" width="350px" height="200px" alt="">
        <p>Your destination email: </p>
        <input name="email" type="text" id="emailInput" placeholder="Selected Email">

        <div align="center">
            <h2>Your email details:</h2>
        </div>
        Subject:
        <input type="text" name="subject" placeholder="Enter your subject">
        <br>
        <hr>
        Message:
        <br>
        <textarea name="message" placeholder="Enter your message"></textarea>
        <button type="submit" onclick="sendEmail()">Send Email</button>
        <br>
        <a href="{% url "home_app:main" %}">Main Page</a>
    </form>
</div>

<script>
    function updateEmail() {
        const emailSelect = document.getElementById('emailSelect');
        const emailInput = document.getElementById('emailInput');
        emailInput.value = emailSelect.value; // Update textbox with selected email
    }

    function sendEmail() {
        const selectedEmail = document.getElementById('emailInput').value;
        if (selectedEmail) {
            alert('Email will be sent to: ' + selectedEmail);
        } else {
            alert('Please select an email before sending.');
        }
    }
</script>

</body>
</html>